Controllers films users
alex9379992/java-filmorate pull request #1
Opened 2022-10-10 19:24 UTC by alex9379992

2022-10-10 19:32 UTC, alex9379992 commented
Добавлены User и Film контроллеры.

2022-10-11 20:57 UTC, andrew-larkin requested changes
Привет! Очень качественная реализация, только переменные в моделях не стоит делать final - это поправить и работа будет принята.

2022-10-11 20:57 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private final String name;
в классах моделей сами переменные не должны быть final, это просто не требуется

2022-10-11 20:57 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final String email;
также убрать в переменных final

2022-10-26 09:50 UTC, merged